### ISSUE TITLE
Training process get killed if --valid is turned on

### ISSUE THREAD

**Issue by txsun1997** [awslabs/dgl-ke#106]
When `--valid` / `--test` is turned on, the training process will get killed during evaluation. To solve this, `--batch_size_eval` and `--neg_sample_size_eval` should be the same value.

**Comment by aksnzhy** [comment]
Actually, the problem is that if we delete `--neg_sample_size_eval` argument and use the default value. The program will be crashed. @zheng-da Could you please check out this issue?

**Comment by classicsong** [comment]
This is a duplicated issue of #101
