### ISSUE TITLE
The loss function issue which is not the same as TransE 

### ISSUE THREAD

**Issue by Zarca** [awslabs/dgl-ke#109]
Hi,
These days I have been using the out-of-box TransE algorithm come with DGL-KE , thanks for your excellent and kind work ! 
However, I also encountered a quesion about the loss funciton while I am tracing down to the source code about it in the: 
**dklke/models/general_models.py** in method forward, lines between 370 and 399 as figures listed below:

![DGL_ISSUE](https://user-images.githubusercontent.com/24642659/84146980-2c63ba80-aa8f-11ea-90ef-4336106802fb.PNG)

![DGL_ISSUE2](https://user-images.githubusercontent.com/24642659/84146989-31c10500-aa8f-11ea-901a-902164932be3.PNG)

It seems that it's NOT consistent with  the loss function described in the paper on dgl-ke's official github homepage, as the figure showed below:

![DGL_ISSUE4](https://user-images.githubusercontent.com/24642659/84147508-199db580-aa90-11ea-9eb3-a4d19915a087.PNG)

In this paper, the loss you author declared to be usued has just these 2 forms as below:
![DGL_ISSUE3](https://user-images.githubusercontent.com/24642659/84148019-ef002c80-aa90-11ea-9991-d25f9818f220.PNG)

but is not the same with the implemented as I mentioned above in dgk-ke's source code,
so I'm wondering that why the source code of general_models.py has changed the loss form?
Dose it make any improvement compared with the oringinal two kind of loss function in your paper?

Looking forward your reply

**Comment by classicsong** [comment]
The adversarial sampling is in **3.3 Negative sampling** in the paper.
It is not a uniform sampling.
