### ISSUE TITLE
The Bin Path Issue in dist_train.py line 79 

### ISSUE THREAD

**Issue by Zarca** [awslabs/dgl-ke#117]
Hi,
I noticed that when use the distribution train, when launch the kvstore server and client, it seems that 
the bin path is fixed to within "**/usr/local/bin:/bin:/usr/bin:/sbin/**"  in dglke/dist_train.py like  below:
https://github.com/awslabs/dgl-ke/blob/ad4be69b99240f5eede28700bdb6db109973140f/python/dglke/dist_train.py#L79

however, if the user's develop environment is conda, is may cause some problem.
For me ,I use conda as my python environment,
so the two executable files named **dglke_server** and **dglke_clinet** is automatically loacated in "**/root/miniconda3/bin/"** directory , so it will cause this two files can't be launch correctly.

I suggest that ,maybe when it comes to the path setting, it should add some code to find the **right** path of dglke's running executable files like dglke_server etc.

Is that right?

**Comment by classicsong** [comment]
Currently DGL-ke does not provide conda install. We will provide it latter. Sorry for the inconvenience.

**Comment by classicsong** [comment]
You need to add it into your PATH environment manually.

**Comment by Zarca** [comment]
@classicsong Thanks a lot man XD
