### ISSUE TITLE
Something wrong with RotatE score function

### ISSUE THREAD

**Issue by y820895863** [awslabs/dgl-ke#131]
Thanks for contributing such wonderful work! There is an error when I run RotatE using command "DGLBAKEND=pytorch dglke_train --model_name RotatE", which shows:
  File ".../dglke/models/pytorch/score_fun.py", line 423, in edge_func
    re_score = re_head * re_rel - im_head * im_rel
RuntimeError: The size of tensor a (200) must match the size of tensor b (400) at non-singleton dimension 1
In the paper RotatE it only rotates the head and it seems there is some change in this implement, so I don't know how to fix it. I wonder if you could help me.

**Comment by classicsong** [comment]
For RotatE, you need an extra arguments `-de` to double entitiy dim for complex number It is used by RotatE.

**Comment by y820895863** [comment]
Got it, thank you very much.

**Comment by Ashutosh2407** [comment]
> For RotatE, you need an extra arguments `-de` to double entitiy dim for complex number It is used by RotatE.

is it the same with transR?
