### ISSUE TITLE
justification for choice of --neg_sample_size_eval

### ISSUE THREAD

**Issue by dchang56** [awslabs/dgl-ke#132]
I understand that when working with larger KGs, it's convenient to set a neg_sample_size_eval that's smaller than num_entities in order to speed up link prediction in evaluation.

However, having a smaller neg_sample_size_eval also means potentially inflating link prediction results (if I evaluate each positive triple against only 1000 negative triples among 200k potential negative samples, the model will likely get higher evaluation metrics). So there's a tradeoff between faster evaluation and less biased evaluation metrics.

How do you deal with this tradeoff and justify using a certain value for the hyperparameter? Do we just assume that neg_sample_size_eval of 10000 is sufficient to approximate the true metrics?

**Comment by classicsong** [comment]
This params is tunable.
It trades speed with profiling acc.
