### ISSUE TITLE
killed without trace back

### ISSUE THREAD

**Issue by Yansera** [awslabs/dgl-ke#133]
Hello!

When using the framework, I encountered the following problem: 
This process was automatically killed, and the error report did not provide effective information, so I hope you can help.

Thanks in advance

:)

```
(dglke_env) YCHABOT@25f55d9cb3bd:~/WikiData$  dglke_train --model_name TransE_l2 --data_path ~/WikiData/ \
> --dataset wikidata_input_nohead.csv --delimiter , \
> --data_files ~/WikiData/wikidata_input_nohead.csv ~/WikiData/wikidata_test.csv ~/WikiData/wikidata_valid.csv \
> --format raw_udd_hrt --batch_size 512 --log_interval 1000 --neg_sample_size 25600 --batch_size_eval 25600 \
> --regularization_coef=1e-9 --hidden_dim 300 --gamma 19.9 --lr 0.25 --batch_size_eval 16 --test -adv \
> --gpu 0 1 2 3 --max_step 6000 --async_update
Reading train triples....
Finished. Read 491065553 train triples.
Reading valid triples....
Finished. Read 70000 valid triples.
Reading test triples....
Finished. Read 70000 test triples.
|Train|: 491065553
random partition 491065553 edges into 4 parts
part 0 has 122766389 edges
part 1 has 122766389 edges
part 2 has 122766389 edges
part 3 has 122766386 edges
/home/YCHABOT/anaconda3/envs/dglke_env/lib/python3.6/site-packages/dgl/base.py:25: UserWarning: multigraph will be deprecated.DGL will treat all graphs as multigraph in the future.
  warnings.warn(msg, warn_type)
|valid|: 70000
|test|: 70000
Killed
```

**Comment by zheng-da** [comment]
it seems that it runs out of memory. could you provide more details? for example, what is the memory size?

**Comment by Yansera** [comment]
Thank you for your reply. The machine I am using has 120G of RAM. The target triples to be trained are 11G in total, including 491065553 edges.

**Comment by zheng-da** [comment]
what is the number of entities? the entity embeddings usually account for most of the memory consumption. i see you use 300 dimensions.

**Comment by Yansera** [comment]
Sry I did not precise it.
For the number of entities, it is about 80 million.

**Comment by zheng-da** [comment]
your entity embeddings are 80M * 300 * 4=96GB. adding memory consumption by the graph structure (11GB), the total memory consumption is very close to 120GB. i don't think your machine has enough memory to train a KG of this size with DGL-KE.

**Comment by Yansera** [comment]
Thank you very much for your reply

**Comment by zheng-da** [comment]
could you use "top" to check the memory consumption? how much memory was free when you ran DGL-KE?

**Comment by Yansera** [comment]
The 50-dimensional model crashed when the memory was loaded to 120G. 
Thank you for your reminder. It is a memory problem. ：）
