### ISSUE TITLE
ERROR: mxnet 1.6.0 has requirement requests<2.19.0,>=2.18.4, but you'll have requests 2.24.0 which is incompatible.

### ISSUE THREAD

**Issue by StevenJokes** [awslabs/dgl-ke#134]
****
![image](https://user-images.githubusercontent.com/25657787/90340341-0d9f1880-e02a-11ea-8e4d-634b5357151a.png)

**Comment by classicsong** [comment]
DGL-KE did not test on MXNet-1.6.
Please use MXNet-1.5.

**Comment by StevenJokes** [comment]
OK.
