### ISSUE TITLE
Can not import function load_raw_emb_data

### ISSUE THREAD

**Issue by MathildaSu** [awslabs/dgl-ke#143]
Hi, I'm trying to use function [`load_raw_emb_data`](https://github.com/awslabs/dgl-ke/blob/32adef91d2f115ea21647302e64c893034183b09/python/dglke/utils.py#L172), But `from dglke.utils import load_raw_emb_data` gives error `ImportError: cannot import name 'load_raw_emb_data'`

and ```import dglke.utils as utils 

utils.load_raw_emb_data``` gives error
`AttributeError: module 'dglke.utils' has no attribute 'load_raw_emb_data'`

Do you know when will this function be available? Thanks

**Comment by classicsong** [comment]
Currently DGL-KE is deployed as a cmdline toolkit. It does not work as the library, we are planing to make it as a library (that you can use dglke.utils.load_raw_emb_data) in 0.2.

**Comment by MathildaSu** [comment]
Ok, Thanks for clarification.
