### ISSUE TITLE
How to interpret score value

### ISSUE THREAD

**Issue by akastrin** [awslabs/dgl-ke#155]
Suppose that one of the prediction algorithm returns the following values:
```
src  rel  dst   score
 1    0    12   -4.11393
 1    0    18   -6.10925
 1    0    13   -3.66778
```
I'm not quite sure how to interpret the score value: lower the score (more negative) greater the likelihood that prediction is true or vice versa? (So in the example above the relation 1-0-18 is more probable that relation 1-0-13?)

Thanks, Andrej

**Comment by classicsong** [comment]
The larger the score (closer to 0) the better. So in Your example, 1-0-13 is more likely to be connected than 1-0-12 and 1-0-12 is more likely than 1-0-18.

**Comment by akastrin** [comment]
Thanks!

**Comment by FilipKon** [comment]
> The larger the score (closer to 0) the better. So in Your example, 1-0-13 is more likely to be connected than 1-0-12 and 1-0-12 is more likely than 1-0-18.

Hey,

but this is true if the scoring function is logsigmoid is that correct ? I'm training with RESCAL and if I create the prediction with and without the scoring function then I see that without the logsigmoid the bigger the number the better it is. And my other question would be if the exist min and max values for the predictions ?

Thanks.
Best, Filip
