### ISSUE TITLE
arguments error in notebook-example's inference code

### ISSUE THREAD

**Issue by SoMinHyung** [awslabs/dgl-ke#160]
In notebook-examples/kge_wikimedia.ipynb

There is a code block  like

    # Using PyTorch Backend
    !DGLBACKEND=pytorch dglke_emb_sim --model_path ./wikimedia/TransE_l2_wikimedia_0/ \
    --format 'h_*_*' --data_files head.list \
    --score_func none --topK 10 --gpu 0

And when I run this Error like this appears

    usage: dglke_emb_sim [-h] [--mfile MFILE] [--emb_file EMB_FILE]
                         [--format FORMAT]
                         [--data_files DATA_FILES [DATA_FILES ...]] [--raw_data]
                         [--exec_mode EXEC_MODE] [--topK TOPK]
                         [--sim_func SIM_FUNC] [--output OUTPUT] [--gpu GPU]
    dglke_emb_sim: error: unrecognized arguments: --model_path ./wikimedia/TransE_l2_wikimedia_0/ --score_func none

And it seems there aren't args like 'score_func' and 'model_path'.

To which args should I change?

**Comment by JustinRong** [comment]
I also encountered this problem, have you solved it? How to solve it

**Comment by JustinRong** [comment]
I know, use dglke_predict command instead
