### ISSUE TITLE
stuck in save model steps

### ISSUE THREAD

**Issue by Reid00** [awslabs/dgl-ke#175]
my result stuck in save model, it should be exit the program, but stuck.
![image](https://user-images.githubusercontent.com/38450639/102035937-a426ef00-3dfc-11eb-9046-a3dce19bb28b.png)

i check the model save path , the relative files is saved.
![image](https://user-images.githubusercontent.com/38450639/102036111-fbc55a80-3dfc-11eb-8545-5d4d2a558ef2.png)

**Comment by classicsong** [comment]
It maybe in testing. Testing is costly especially your graph is very large. You can set neg_sample_size_eval to 10000 for example.

**Comment by Reid00** [comment]
DGLBACKEND=pytorch dglke_train --model_name TransE_l2 --dataset patient --batch_size 1000 --neg_sample_size 200 --hidden_dim 400 --gamma 19.9 --lr 0.25 --max_step 24000 --log_interval 100 --batch_size_eval 16 -adv --regularization_coef 1.00E-09 --test --gpu 0 --mix_cpu_gpu --data_path ./data/ --format raw_udd_hrt --data_files train.txt valid.txt test.txt --neg_sample_size_eval 10000

this is my commad, i have set neg_sample_size_eval 10000

**Comment by classicsong** [comment]
You need to check if CPU usage is very high when it is 'stucked'

**Comment by Reid00** [comment]
Got it, thank you a million.
