### ISSUE TITLE
embeddings initialization

### ISSUE THREAD

**Issue by Antares-97** [awslabs/dgl-ke#177]
Hi! Is there a way to initialize the embeddings from external files? And how can I initialize the node and relation embeddings?

**Comment by classicsong** [comment]
Right now you have to change the code to add support for loading your own node and relation embeddings. You can do that after here: https://github.com/awslabs/dgl-ke/blob/b34bf1d538a3a2184a4e767aeaa3998ed290233e/python/dglke/train_pytorch.py#L281
