### ISSUE TITLE
DGLHeteroGraph object has no attribute 'copy_from_parent'

### ISSUE THREAD

**Issue by ryantd** [awslabs/dgl-ke#199]
run `dglke_partition --dataset FB15k -k 4 --data_path data` will raise an error of `AttributeError: 'DGLHeteroGraph' object has no attribute 'copy_from_parent'`

https://github.com/awslabs/dgl-ke/blob/720b6fc771e4735e925193323e79fbe13f2c88eb/python/dglke/partition.py#L132

The [ref](https://discuss.dgl.ai/t/copying-subgraph-features-to-parent-in-dgl0-5-0/1223) means that 'copy_from_parent' is deprecated?

**Comment by classicsong** [comment]
Which DGL version you are using? DGL-KE now is only compatible with DGL 0.4.3post2.

**Comment by ryantd** [comment]
@classicsong thanks a lot. I used an incompatible version, which is 0.6.1
Closed
