### ISSUE TITLE
What is the key technologies for training speed increase？

### ISSUE THREAD

**Issue by quqxui** [awslabs/dgl-ke#215]
Hi, Thanks very much for your excellent job!

I'm now using my own algorithm on a large knowledge graph dataset, I've been obsessed with computation time. Since you don't support any function API, i want to change the source code. 

I'm worried that my changes will slow down the running speed, so I'd like to ask you what is the key technologies for training speed increase？If I change the model, will it lead to the key technologies change? 

Hope for your reply. 
Best.

**Comment by classicsong** [comment]
You can look at this paper: https://arxiv.org/abs/2004.08532

The most important thing is you need to make sure your score function is implemented efficiently. Then KGE framework will handle other parts.

**Comment by quqxui** [comment]
I found if i set `--neg_sample_size_eval=-1`, the eval time in a big knowledge graph(400k test triplets) is very slow.  It's going to take hours. Can I increase the test speed in any way?   

And what if the `--batch_size_eval`bigger or smaller than `--neg_sample_size_eval`?

**Comment by classicsong** [comment]
--neg_sample_size_eval = -1 means use all the nodes during evaluatoin. when the graph is large, it will be very time consuming.
