### ISSUE TITLE
Issues with dglke_eval and dglke_predict

### ISSUE THREAD

**Issue by DJRavinszkha** [awslabs/dgl-ke#219]
Hello Again,

I have been attempting to run the dglke_eval and dglke_predict functions on my pretrained model, however am encountering the following errors:

dglke_eval:
<img width="1062" alt="Screenshot 2021-06-14 at 10 46 23 PM" src="https://user-images.githubusercontent.com/29537935/122364510-1cac6b00-cf5a-11eb-94e7-8e706da3e247.png">

dglke_predict:
<img width="1080" alt=" " src="https://user-images.githubusercontent.com/29537935/122364567-28982d00-cf5a-11eb-9aeb-f61fa537b92f.png">

As you can see I have pytorch version 1.6 installed, as I could see this was the best version for dglke.

In addition to this, I am using the entities.tsv and relations.tsv initialised by dglke_train and my own list of heads, relations and tails. After running dglke_train successfully, the following output was saved:
Screenshot 2021-06-14 at 10 46 17 PM
and I expect the result of dglke_eval to be the same to this value.
<img width="346" alt="Screenshot 2021-06-14 at 10 46 17 PM" src="https://user-images.githubusercontent.com/29537935/122364621-32219500-cf5a-11eb-9922-dafa89074ef6.png">

Thanks for your help in advance!

**Comment by classicsong** [comment]
It seems the data loader did not split the dataset correctly. Can you check the data and the delimiter?

**Comment by DJRavinszkha** [comment]
Everything I have used is the same as in the dglke_train, therefore I don't see what I have done wrong.

**Comment by classicsong** [comment]
For dglke_predict, can you take a look of the config.json? Does it has a field called model_name?

**Comment by classicsong** [comment]
BTW, which train script you are using?
