### ISSUE TITLE
Interpretation of edge importance scores

### ISSUE THREAD

**Issue by thomasthomasth** [awslabs/dgl-ke#249]
Hi,

Could you please speficy how to define edge important scores? This is an optinal parameter of the any of the models (TranE, Rotat, etc.) 

I didn't find anything about this in the documentation.

An edge _e1_ with value 1.0 has a larger importance than another edge _e2_ with value 2.0? Or it should be interpreted the other way around?

**Comment by classicsong** [comment]
The higher the value, the more important the edge is.

**Comment by thomasthomasth** [comment]
@classicsong Thank you!
