### ISSUE TITLE
Adding node features and edge weights in TransE Embeddings

### ISSUE THREAD

**Issue by Maristela-de-Jesus** [awslabs/dgl-ke#251]
Hi, 
I am following this tutorial https://github.com/awslabs/dgl-ke/blob/master/notebook-examples/kge_wikimedia.ipynb to create Knowledge Graph Embeddings with my data. As the tutorial example, I implemented TransE with my dataset head, relation, and tail. However, my graph also has nodes features and edge weights. Is there a way to add the nodes' features and edge weights to my graph? 

Thanks!

**Comment by thomasthomasth** [comment]
@Maristela-de-Jesus 

Please take a look at the parameter _**has_edge_importance**_ here:

https://aws-dglke.readthedocs.io/en/latest/train.html

I think this answers your question about edge weights.

Regarding your other question - my guess is that you need to split up your graph and turn your node features into multiple nodes.

Say, if a node represents a city and the node feature is 'is_capital_of" then the node feature points to a country. Maybe it will be computationally expensive to come up with this graph that I am proposing but the advantage is that this country will be represented by a single entity only.

**Comment by Maristela-de-Jesus** [comment]
Thank you @thomasthomasth
