### ISSUE TITLE
Make dgl-ke deterministic

### ISSUE THREAD

**Issue by fburdet** [awslabs/dgl-ke#252]
Dear all,

I'm trying to make dglk-ke deterministic (ie launch 2x the same dglke_train command, calculate the scores for the same edges and get exactly the same score). That would sound like more than a nice to have...

I tried some of the tips in
https://github.com/awslabs/dgl-ke/issues/76
that is, 
- add --num_thread 1 --num_proc 1 in the dglke_train command
- modify .local/lib/python3.8/site-packages/torch/backends/cuda/__init__.py that seems to load cuda and added torch.use_deterministic_algorithms(True)

but it doesn't work. Any easier way to make the command deterministic?

Thanks in advance for your help!

**Comment by classicsong** [comment]
The training is also random (edge sampling)

**Comment by fburdet** [comment]
Thanks for the answer, @classicsong ! 

Any way to also set the seed for the edge sampling?

**Comment by classicsong** [comment]
You can try set both numpy and torch seeds.
