### ISSUE TITLE
IndexError: list index out of range when training on raw user defined knowledge graph

### ISSUE THREAD

**Issue by Maester-Khris** [awslabs/dgl-ke#259]
Hello i try to train with my own dataset, but i have one error after the start of triple reading

! sudo pip3 install dgl==0.4.3
#sudo pip3 install dglke
! git clone https://github.com/awslabs/dgl-ke.git
%cd dgl-ke/python
! sudo python3 setup.py install
! pip install ogb

%%time
!DGLBACKEND=pytorch dglke_train \
--dataset mydatas \
--model_name TransE_l2 \
--data_path /content/mydataset/ \
--format raw_udd_hrt \
--data_files train.tsv valid.tsv test.tsv \
--batch_size 1000 \
--neg_sample_size 200 \
--hidden_dim 400 \
--gamma 19.9 \
--lr 0.25 \
--max_step 24000 \
--log_interval 100 \
--batch_size_eval 16 -adv \
--regularization_coef 1.00E-09 \
--test \
--save_path /content/mydataset/ \
--neg_sample_size_eval 10000 

Traceback (most recent call last):
  File "/usr/local/bin/dglke_train", line 33, in <module>
    sys.exit(load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_train')())
  File "/usr/local/lib/python3.7/dist-packages/dglke-0.1.0.dev0-py3.7.egg/dglke/train.py", line 85, in main
  File "/usr/local/lib/python3.7/dist-packages/dglke-0.1.0.dev0-py3.7.egg/dglke/dataloader/KGDataset.py", line 762, in get_dataset
  File "/usr/local/lib/python3.7/dist-packages/dglke-0.1.0.dev0-py3.7.egg/dglke/dataloader/KGDataset.py", line 527, in __init__
  File "/usr/local/lib/python3.7/dist-packages/dglke-0.1.0.dev0-py3.7.egg/dglke/dataloader/KGDataset.py", line 595, in load_entity_relation
IndexError: list index out of range

I need some help to solve this

**Comment by classicsong** [comment]
It seems something wrong here: https://github.com/awslabs/dgl-ke/blob/master/python/dglke/dataloader/KGDataset.py#L594

Can you check if the input file (edges) is correct?

**Comment by Maester-Khris** [comment]
Thank you for answering.
I used the data provided in one of your tutorials to test the training.
Here are the files

**Comment by Maester-Khris** [comment]
Hello, 
Here are the files i used 
![valid](https://user-images.githubusercontent.com/99334316/185631381-de5a9a70-7349-4f4d-8a4d-d2a03bf0959d.PNG)
![test](https://user-images.githubusercontent.com/99334316/185631388-ce574a8e-3c47-4f46-91b4-063dc2f01f7d.PNG)
![train](https://user-images.githubusercontent.com/99334316/185631390-4e31efdf-cd34-4837-88d7-9250f264f304.PNG)

**Comment by Maester-Khris** [comment]
Hello i changed the content of files and precise the delimiter to , in the command traing
