### ISSUE TITLE
Can not install dgl 0.4.3

### ISSUE THREAD

**Issue by AprLie** [awslabs/dgl-ke#261]
When I try to install dgl 0.4.3 by
```pip3 install dgl==0.4.3```,
it shows that
```
ERROR: Could not find a version that satisfies the requirement dgl==0.4.3 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.6.0, 0.6.0.post1, 0.6.1, 0.9.0)
ERROR: No matching distribution found for dgl==0.4.3
```
And if I install the latest dgl 0.9.0, it will report errors when running the example code.

How can I install dgl 0.4.3?

**Comment by classicsong** [comment]
Can you try pip3 install dgl==0.4.3post2

**Comment by AprLie** [comment]
![image](https://user-images.githubusercontent.com/40601864/188309177-f2e635cf-b053-4b67-ae5e-701eb79b2acb.png)
still can not install with the recommended command.

**Comment by AprLie** [comment]
It works, thanks a lot. One other question is that how to save model parameter(i.e., entity embedding and relation embedding) during training on multi-GPU for early stopping to find the model with best performance on validation set.
