### ISSUE TITLE
DGLBACKEND s not recognized as an internal or external command

### ISSUE THREAD

**Issue by Maester-Khris** [awslabs/dgl-ke#262]
Hello;
I try to use dglke on my computer, but i can't even start the training.
this is the error: 'DGLBACKEND' is not recognized as an internal or external command,
operable program or batch file.

environment;
- Anaconda jupyter
- python 3.7

**Comment by classicsong** [comment]
Actually, dglke only works with PyTorch. You can use the default DGLBACKEND.
