### ISSUE TITLE
DGL Assert fails breaks when setting `exclude_positive=True` in Sampler

### ISSUE THREAD

**Issue by asaluja** [awslabs/dgl-ke#71]
I needed to make some changes to the [train](https://github.com/awslabs/dgl-ke/blob/master/python/dglke/train.py) script, in particular I wanted to change the head and tail samplers in training to `exclude_positive=True` [here](https://github.com/awslabs/dgl-ke/blob/master/python/dglke/train.py#L128) and [here](https://github.com/awslabs/dgl-ke/blob/master/python/dglke/train.py#L136), but as soon as I do that [this assert](https://github.com/dmlc/dgl/blob/0.4.x/src/graph/sampler.cc#L1186) in dgl fails:

```
python3: /opt/dgl/src/graph/sampler.cc:1186: dgl::NegSubgraph dgl::{anonymous}::EdgeSamplerObject::genNegEdgeSubgraph(const dgl::Subgraph&, const string&, int64_t, bool, bool): Assertion `prev_neg_offset + neg_sample_size == neg_vids.size()' failed.
```

Am I using the sampler incorrectly here?

**Comment by classicsong** [comment]
One possibility is that the sampler can not get enough negative nodes for a batch. How large is your graph? Can you try to reduce your batchsize?

**Comment by asaluja** [comment]
I have around 1 million nodes and 4.5 million edges. I don't think it's batch size since I've tried reducing the batch size to 1 and the number of negative samples to 1 and I still get the same error.

**Comment by classicsong** [comment]
I think you can refer to how eval sampler samples edges:
https://github.com/awslabs/dgl-ke/blob/de4e970c9ffa45cae7d74139f4b3b38365f6c3ad/python/dglke/dataloader/sampler.py#L500

This gives another way to exclude positive edges

**Comment by asaluja** [comment]
OK thanks I'll look into that. Wondering though if the above is a bug or if I'm doing something wrong?

**Comment by classicsong** [comment]
You need to use return_false_neg and we will look at if there is any bug in exclude_positive=True
