### ISSUE TITLE
The comparison of speed in document

### ISSUE THREAD

**Issue by wawltor** [awslabs/dgl-ke#72]
I would like to know the more detail about time cost，is  time that the model train each epoch?
<img width="373" alt="图片" src="https://user-images.githubusercontent.com/16698950/78907815-c9b46980-7ab3-11ea-9ce9-14a6a5fd2280.png">

**Comment by aksnzhy** [comment]
This is the total training time running same number of epoch.

**Comment by wawltor** [comment]
> This is the total training time running same number of epoch.

OK，I got it ！
