### ISSUE TITLE
model.predict_score(dt.g) error

### ISSUE THREAD

**Issue by gustavopuma2** [awslabs/dgl-ke#73]
when calling model.predict_score(dt.g) , I receive the following error:
/opt/conda/lib/python3.7/site-packages/dglke/models/pytorch/score_fun.py in <lambda>(edges)
    306 
    307     def forward(self, g):
--> 308         g.apply_edges(lambda edges: self.edge_func(edges))
    309 
    310     def create_neg(self, neg_head):

/opt/conda/lib/python3.7/site-packages/dglke/models/pytorch/score_fun.py in edge_func(self, edges)
    274 
    275     def edge_func(self, edges):
--> 276         real_head, img_head = th.chunk(edges.src['emb'], 2, dim=-1)
    277         real_tail, img_tail = th.chunk(edges.dst['emb'], 2, dim=-1)
    278         real_rel, img_rel = th.chunk(edges.data['emb'], 2, dim=-1)

/opt/conda/lib/python3.7/site-packages/dgl/utils.py in __getitem__(self, key)
    282     def __getitem__(self, key):
    283         if key not in self._keys:
--> 284             raise KeyError(key)
    285         return self._fn(key)
    286 

KeyError: 'emb'

**Comment by zheng-da** [comment]
Hello, thanks for using the package. The first version of DGL-KE actually doesn't define the Python interface. We'll define the Python interface in the next release.

**Comment by classicsong** [comment]
related to #82
