### ISSUE TITLE
Evaluation scheme for larger KBs

### ISSUE THREAD

**Issue by vardaan123** [awslabs/dgl-ke#93]
In the paper, section 5.3, it is mentioned that for the entire Freebase KB, you use a modified evaluation strategy in which

> we use only 2000 negative triplets; 1000 sampled uniformly from the entire set of negative
> samples and 1000 sampled proportionally to the degree of the corrupted entities;

Is this evaluation supported in the dgl-ke library? If so, which arguments can be used to enable this?

**Comment by classicsong** [comment]
you can use this argument --neg_sample_size_eval=1000 and neg_deg_sample_eval=True

**Comment by vardaan123** [comment]
Thanks for your response!

**Comment by vardaan123** [comment]
Hi, for evaluation, I understand that the corrupted entities are a mix of uniformly sampled entities and those sampled based on degree (if I use --neg_sample_size_eval=1000 and neg_deg_sample_eval=True). Is there a way if I want to use just degree-based sampling and no uniformly sampled negative triples for evaluation?

**Comment by classicsong** [comment]
Currently, it does not support certain sampling method. You have to implement it your self.
