### ISSUE TITLE
[Question] --batch_size_eval

### ISSUE THREAD

**Issue by HenryYihengXu** [awslabs/dgl-ke#98]
Is it possible to set this flag to all edges? I mean not by specifying the exact number, but some flags like "all_edges."

**Comment by classicsong** [comment]
This just controls the minibatch size in evaluation to make sure there will not be an OOM problem in evaluation.

**Comment by HenryYihengXu** [comment]
I see. So you are saying if we omit this flag, by default it uses all edges for evaluation right?

**Comment by classicsong** [comment]
The evaluation will use all edges in the evaluation set (you can provide your own eval data) no matter what value you set for batch_size_eval.
